spring.application.name=backend

spring.jpa.database =POSTGRESQL
spring.sql.init.platform=postgres
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
#spring.datasource.url=jdbc:postgresql://localhost:5432/bd_chrono_swap
#spring.datasource.username=postgres
#spring.datasource.password=IngenieroC
spring.datasource.url=${URL_DATABASE}
spring.datasource.username=${USERNAME_DATABASE}
spring.datasource.password=${PASSWORD_DATABASE}
spring.jpa.generate-ddl=true

